[package]
name = "rust-c-ffi-example"
version = "0.1.0"
links = "my_struct"
build = "build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }